#!/usr/bin/env python3
"""Generate fork release notes grouped by conventional commit type.

Fork-only script (saguarocloud/herdr).

This used to borrow `TYPE_ORDER`, `commit_subjects` and `humanize_subject`
from scripts/preview.py. Upstream v0.9.1 deleted all three -- its preview
notes are now just a compare link -- which broke this script and its tests.
The grouping is fork-only behaviour, so it now lives here instead of
depending on upstream internals that can vanish in any sync. Only
`normalize_version` is still borrowed, and it is trivial to inline if that
goes too.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

try:
    from scripts import preview
except ImportError:  # executed directly as scripts/fork_release_notes.py
    import preview

# Subjects generated by release automation itself; never interesting in notes.
HIDDEN_SUBJECTS = (
    "docs: publish release distribution",
    "docs: update website manifest",
    "docs: update preview manifest",
    "chore: approve contributor",
    "chore: approve merged contributor",
)
TYPE_HEADINGS = {
    "feat": "Added",
    "fix": "Fixed",
    "perf": "Performance",
    "docs": "Maintenance",
    "ci": "Maintenance",
    "test": "Maintenance",
    "refactor": "Maintenance",
    "chore": "Maintenance",
}
TYPE_ORDER = ("Added", "Fixed", "Performance", "Maintenance", "Other")

# Everything this script still borrows from upstream's scripts/preview.py.
# Guarded by a test, because upstream deleting a borrowed helper is exactly how
# this script broke during the v0.9.1 sync.
UPSTREAM_PREVIEW_HELPERS = ("normalize_version",)
COMMIT_RE = re.compile(r"^(?P<kind>[a-z]+)(?:\([^)]+\))?!?:\s+(?P<body>.+)$")


def run_git(args: list[str]) -> str:
    return subprocess.check_output(["git", *args], text=True).strip()


def hidden_subject(subject: str) -> bool:
    lowered = subject.strip().lower()
    return any(lowered.startswith(prefix) for prefix in HIDDEN_SUBJECTS)


def commit_subjects(previous: str, commit: str) -> list[str]:
    output = run_git(["log", "--pretty=format:%s", f"{previous}..{commit}"])
    if not output:
        return []
    subjects = []
    for line in output.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if hidden_subject(stripped):
            continue
        subjects.append(stripped)
    return subjects


def humanize_subject(subject: str) -> tuple[str, str]:
    match = COMMIT_RE.match(subject)
    if not match:
        return "Other", subject[0].upper() + subject[1:]
    kind = match.group("kind")
    body = match.group("body").strip()
    heading = TYPE_HEADINGS.get(kind, "Other")
    if body:
        body = body[0].upper() + body[1:]
    else:
        body = subject
    return heading, body


def _is_merge_subject(subject: str) -> bool:
    return subject.lower().startswith("merge ")


def build_fork_notes(
    previous: str,
    commit: str,
    version: str,
    base_version: str,
    repo: str,
) -> str:
    short = commit[:7]
    lines = [
        f"Fork build `{version}`",
        "",
        f"Built from [`{short}`](https://github.com/{repo}/commit/{commit}) on `master`.",
        f"Base version: {preview.normalize_version(base_version)}",
    ]
    if previous:
        lines.append(f"Compare: https://github.com/{repo}/compare/{previous}...{commit}")
    lines.append("")

    grouped: dict[str, list[str]] = {heading: [] for heading in TYPE_ORDER}
    if previous:
        for subject in commit_subjects(previous, commit):
            if _is_merge_subject(subject):
                continue
            heading, body = humanize_subject(subject)
            grouped.setdefault(heading, []).append(body)

    wrote = False
    for heading in TYPE_ORDER:
        items = grouped.get(heading, [])
        if not items:
            continue
        wrote = True
        lines.append(f"### {heading}")
        for item in items:
            lines.append(f"- {item}")
        lines.append("")

    if not wrote:
        lines.extend(["### Changed", "- Rebuilt fork artifacts from master.", ""])

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--previous", default="", help="previous fork release tag; empty for the first release")
    parser.add_argument("--commit", required=True, help="full commit SHA being released")
    parser.add_argument("--version", required=True, help="fork version, e.g. 0.7.3-f2634a6")
    parser.add_argument("--base-version", required=True, help="Cargo.toml base version")
    parser.add_argument("--repo", required=True, help="owner/name of the fork repository")
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    notes = build_fork_notes(
        previous=args.previous.strip(),
        commit=args.commit,
        version=args.version,
        base_version=args.base_version,
        repo=args.repo,
    )
    args.output.write_text(notes, encoding="utf-8")
    print(notes, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
